# Apply with:
#   kubectl apply -f <this-config>
# NOTE: this overrides whatever config you already have for Prometheus
# adapter, so you may want to merge them first.
#
# Redeploy adapter for new config to be taken into account:
#   kubectl delete -f /path/to/prometheus-adapter-deployment.yaml
#   kubectl create -f /path/to/prometheus-adapter-deployment.yaml
# Check resulting metrics:
#   kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/ | jq
#   kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/<namespace>/<objtype>/*/<metric>?labelSelector=app=<name>" | jq
# E.g:
#   kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/monitoring/service/*/hpa_queue_all" | jq
#
# (It may be possible to override namespace in case HPA controlled deployment
# is in another namespace from the metric provider.)
apiVersion: v1
data:
  config.yaml: |
      rules:
      - seriesQuery: '{__name__="hpa_queue_all"}'
        metricsQuery: hpa_queue_all{<<.LabelMatchers>>}
        name:
          matches: ^hpa_queue_all
          as: "hpa_queue_all"
        resources:
          # HPA needs both namespace + suitable object resource for its query paths:
          # /apis/custom.metrics.k8s.io/v1beta1/namespaces/monitoring/service/*/hpa_queue_all
          # (pod is not suitable object type for matching as each instance has different name)
          overrides:
            namespace:
              resource: namespace
            service:
              resource: service
      - seriesQuery: '{__name__="hpa_queue_waiting"}'
        metricsQuery: hpa_queue_waiting{<<.LabelMatchers>>}
        name:
          matches: ^hpa_queue_waiting
          as: "hpa_queue_wait_count"
        resources:
          overrides:
            namespace:
              resource: namespace
            service:
              resource: service
      - seriesQuery: '{__name__="hpa_queue_maxwait_seconds"}'
        metricsQuery: hpa_queue_maxwait_seconds{<<.LabelMatchers>>}
        name:
          matches: ^hpa_queue_maxwait_seconds
          as: "hpa_queue_wait_time"
        resources:
          overrides:
            namespace:
              resource: namespace
            service:
              resource: service
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: monitoring
