apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scalability-tester-frontend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scalability-tester-frontend
subjects:
- kind: ServiceAccount
  name: scalability-tester-frontend-sa
  namespace: monitoring
