apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scalability-tester-frontend
  namespace: monitoring
spec:
  endpoints:
  - interval: 4s
    port: metrics
    relabelings:
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: node
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: scalability-tester-frontend
