apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scalability-tester-backend-sleep
  namespace: monitoring
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scalability-tester-backend-sleep
  minReplicas: 1
  maxReplicas: 64
  metrics:
  - type: External
    external:
      metric:
        name: hpa_queue_wait_count
        selector:
          # match queue "name" label for the metric
          matchLabels:
            name: sleep
      target:
        # number of queue items per worker
        type: Value
        value: 2
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
      - type: Percent
        value: 100
        periodSeconds: 5
    scaleUp:
      selectPolicy: Max
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 5
      - type: Pods
        value: 4
        periodSeconds: 5
